<?php
namespace Postman\Configuration;


require_once '/var/www/Postman/src/Postman/Configuration/Parser.php';

/**
 * Test class for Parser.
 * Generated by PHPUnit on 2011-08-31 at 18:08:05.
 */
class ParserTest extends \TestCase
{
    /**
     * @var Parser
     */
    protected $object;

    protected $eventFired = false;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();

        $this->container['event_dispatcher']->addListener('postman.load_configuration.uri_filter', array($this, 'listen'));
        
        $this->object = new Parser($this->container);
        $this->object->parse(array(
            'config' =>
            array(
                'listen' => '192.168.1.5',
                'port' => 8081,
                'basedir' => '/var/www/pkb/web',
                'timeout' => 72000,
            ),
            'uri_filter' =>
                array(
                    'skip_real_files' => true,
                    'directory_index' => 'app_dev.php',
                    'rules' =>
                array(
                    0 =>
                        array(
                            'pattern' => '^(.*)$',
                            'destination' => '/app.php',
                        ),
                ),
            ),
            'services' =>
                array(
                    'response_providers' =>
                        array(
                            'file' => '\\Postman\\Response\\Provider\\File',
                            404 => '\\Postman\\Response\\Provider\\Error404',
                        ),
                    'processors' =>
                        array(
                            'PHP' => '\\Postman\\Processor\\PHP',
                        ),
                    'filters' =>
                        array(
                            'URI' => '\\Postman\\Request\\Filter\\UriFilter',
                        ),
                ),
        ));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function listen()
    {
        $this->eventFired = true;
    }

    public function testParse()
    {
        $this->assertEquals($this->container->getParameter('listen'), '192.168.1.5');
        $this->assertTrue($this->eventFired);
    }
}

?>
