<?php
namespace Postman\Container;

/**
 * Test class for Container.
 * Generated by PHPUnit on 2011-09-01 at 11:43:58.
 */
class ContainerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Container
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Container;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetParameter().
     */
    public function testGetParameter()
    {
        $this->object->setParameter('a', 'b');
        $this->assertSame('b', $this->object->getParameter('a'));
        $this->assertNull($this->object->getParameter('foo', null));
    }

    /**
     * @todo Implement testHasParameter().
     */
    public function testHasParameter()
    {
        $this->object->setParameter('a', 'b');
        $this->assertTrue($this->object->hasParameter('a'));
        $this->assertFalse($this->object->hasParameter('foo'));
    }
}
?>
